steps:

  - script: $(Build.Repository.LocalPath)\\Scripts\\NukeBuildOutputs.bat
    displayName: Delete previous build outputs
    continueOnError: true

  - task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@2
    displayName: 'Install signing plugin'
    inputs:
      signType: 'test'
    condition: and(succeeded(), eq(variables['SignBuild'], '1'))

  - script: $(Build.Repository.LocalPath)\Scripts\BuildScalarForWindows.bat $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Run Scalar build script ($(configuration))

  - script: $(Build.Repository.LocalPath)\Scripts\RunUnitTests.bat $(configuration)
    displayName: Run unit tests

  - task: PublishTestResults@2
    displayName: Publish unit test results
    inputs:
      testRunner: NUnit
      testResultsFiles: "**\\TestResult.xml"
      searchFolder: $(System.DefaultWorkingDirectory)
      testRunTitle: Windows $(configuration) Unit Tests
      publishRunAttachments: true

  - script: $(Build.Repository.LocalPath)\Scripts\CI\CreateBuildDrop.bat $(configuration) $(Build.ArtifactStagingDirectory)\Tests
    displayName: Create functional test drop

  - task: PublishBuildArtifacts@1
    displayName: Publish functional test drop
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)\Tests
      artifactName: "FunctionalTests_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))

  - script: $(Build.Repository.LocalPath)\Scripts\CI\CreateInstallerDrop.bat $(configuration) $(Build.ArtifactStagingDirectory)\Installers
    displayName: Create installer drop

  - task: PublishBuildArtifacts@1
    displayName: Publish installers
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)\Installers
      artifactName: "Installers_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: and(succeeded(), eq(variables['configuration'], 'Release'))
