steps:

  - script: $(Build.Repository.LocalPath)\\Scripts\\NukeBuildOutputs.bat
    displayName: Delete previous build outputs
    continueOnError: true

  - powershell: |
      & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sn.exe' -Vr *,31bf3856ad364e35
      & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe' -Vr *,31bf3856ad364e35
    displayName: Disable strong name validation for MS delay-signed assemblies

  - script: $(Build.Repository.LocalPath)\Scripts\BuildGVFSForWindows.bat $(configuration) $(majorAndMinorVersion).$(revision)
    displayName: Run VFSForGit build script ($(configuration))

  - script: $(Build.Repository.LocalPath)\Scripts\RunUnitTests.bat $(configuration)
    displayName: Run unit tests

  - task: PublishTestResults@2
    displayName: Publish unit test results
    inputs:
      testRunner: NUnit
      testResultsFiles: "**\\TestResult.xml"
      searchFolder: $(System.DefaultWorkingDirectory)
      testRunTitle: Windows $(configuration) Unit Tests
      publishRunAttachments: true

  - script: $(Build.Repository.LocalPath)\Scripts\CI\CreateBuildDrop.bat $(configuration) $(Build.ArtifactStagingDirectory)\Tests
    displayName: Create functional test drop.

  - task: PublishBuildArtifacts@1
    displayName: Publish functional test drop artifact.
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)\Tests
      artifactName: "FunctionalTests_$(platformFriendlyName)_$(configuration)"
      parallel: true
      parallelCount: 8
    condition: succeededOrFailed()
